In [ ]:
Task 1: Create Database (employees.db)

In [1]:
# Import libraries
import sqlite3
import random
import pandas as pd

# Create database
conn = sqlite3.connect('employees.db')
cursor = conn.cursor()

# Create table
cursor.execute('''
CREATE TABLE IF NOT EXISTS employees (
    emp_id INTEGER PRIMARY KEY,
    name TEXT,
    department TEXT,
    salary REAL,
    years_experience INTEGER,
    performance_score REAL
)
''')

# Departments list
departments = ['Engineering', 'Sales', 'Marketing', 'HR', 'Finance']

# Insert 40 records
for i in range(1, 41):
    name = f'Employee_{i}'
    department = random.choice(departments)
    salary = random.randint(50000, 150000)
    years_experience = random.randint(1, 15)
    performance_score = round(random.uniform(1.0, 5.0), 2)

    cursor.execute('''
    INSERT INTO employees (emp_id, name, department, salary, years_experience, performance_score)
    VALUES (?, ?, ?, ?, ?, ?)
    ''', (i, name, department, salary, years_experience, performance_score))

conn.commit()

Task 2: SQL Queries + Load into Pandas

query 1

In [2]:
query1 = '''
SELECT name, department, salary, performance_score
FROM employees
WHERE performance_score >= 4.0 AND years_experience >= 3
ORDER BY performance_score DESC
LIMIT 15
'''

df_q1 = pd.read_sql_query(query1, conn)
df_q1

          name   department    salary  performance_score
0  Employee_13    Marketing  148526.0               4.99
1   Employee_5      Finance   77782.0               4.79
2  Employee_30           HR  130335.0               4.51
3  Employee_38  Engineering  129676.0               4.40
4  Employee_39           HR   75172.0               4.27
5  Employee_23    Marketing   88427.0               4.08
6  Employee_27      Finance  106732.0               4.08
7   Employee_6           HR  123310.0               4.07

Query 2

In [3]:
query2 = '''
SELECT *
FROM employees
WHERE salary BETWEEN 70000 AND 110000
AND department IN ('Engineering', 'Sales')
ORDER BY department ASC, salary DESC
'''

df_q2 = pd.read_sql_query(query2, conn)
df_q2

,emp_id,name,department,salary,years_experience,performance_score
0,8,Employee_8,Engineering,95176.0,7,3.29
1,1,Employee_1,Engineering,85637.0,4,1.65
2,40,Employee_40,Engineering,70020.0,5,3.21
3,31,Employee_31,Sales,97337.0,5,2.47
4,11,Employee_11,Sales,90988.0,4,3.23
5,17,Employee_17,Sales,78962.0,12,3.16
6,26,Employee_26,Sales,74665.0,10,2.30

Query 3

In [4]:
query3 = '''
SELECT department, COUNT(*) AS employee_count, AVG(salary) AS avg_salary
FROM employees
GROUP BY department
ORDER BY avg_salary DESC
'''

df_q3 = pd.read_sql_query(query3, conn)
df_q3

    department  employee_count     avg_salary
0           HR               3  109605.666667
1    Marketing              15  102604.066667
2  Engineering               9   99119.222222
3        Sales               5   91141.600000
4      Finance               8   88411.000000

ask 3: Pandas Analysis
 Average Performance Score by Department

In [5]:
df = pd.read_sql_query("SELECT * FROM employees", conn)

avg_perf = df.groupby('department')['performance_score'].mean()
avg_perf

department
Engineering    2.632222
Finance        3.076250
HR             4.283333
Marketing      3.260667
Sales          2.688000
Name: performance_score, dtype: float64

Replicate Query 1 Using ONLY Pandas

In [6]:
df_pandas_q1 = df[
    (df['performance_score'] >= 4.0) &
    (df['years_experience'] >= 3)
][['name', 'department', 'salary', 'performance_score']]

df_pandas_q1 = df_pandas_q1.sort_values(
    by='performance_score', ascending=False
).head(15)

df_pandas_q1

           name   department    salary  performance_score
12  Employee_13    Marketing  148526.0               4.99
4    Employee_5      Finance   77782.0               4.79
29  Employee_30           HR  130335.0               4.51
37  Employee_38  Engineering  129676.0               4.40
38  Employee_39           HR   75172.0               4.27
22  Employee_23    Marketing   88427.0               4.08
26  Employee_27      Finance  106732.0               4.08
5    Employee_6           HR  123310.0               4.07

SQL and Pandas are both powerful tools for data analysis but differ significantly in syntax and use cases. In SQL, conditions are written using operators like =, AND, and clauses such as ORDER BY, whereas in Pandas, conditions use ==, &, and functions like .sort_values(). SQL queries are declarative, meaning you specify what result you want, while Pandas is more procedural, requiring step-by-step operations.

SQL is best suited for working with structured data stored in relational databases. It is highly efficient for querying large datasets because the database engine optimizes execution and can handle data that does not fit into memory. On the other hand, Pandas is ideal for in-memory data manipulation, exploratory data analysis, and complex transformations due to its flexibility and integration with Python.

For datasets that are too large to fit into memory, SQL is the better choice because it processes data directly on disk without loading everything into RAM. Pandas can struggle with very large datasets unless combined with tools like Dask. Overall, SQL is preferred for data retrieval and filtering, while Pandas excels in detailed analysis and data processing tasks.